### PR TITLE
fix(webapp): quiz marker remember manual verifications and de-verifications

### LINKED ISSUE #68: Manually verified answers return to incorrect when other answers arrive
As a QM I want to be able to mark answers as correct before all answers have arrived or before timer runs out,  

Currently, QM can mark an non-exact answer as correct (green),  but when another answer arrives, the previously manually verified nanswer will go back to incorrect (red)

See gif

marking

### PR DESCRIPTION
**Pull request by richielewis**
On Quiz Marker screen
Manual verifications and de-verifications are now remembered when new responses arrive.  
Fixes #68

### CODE REVIEW

File: quizmaster-client-app/src/components/QuizHosting/QuestionMarker.tsx [hunk 1]
```diff
@@ -285,22 +297,24 @@ export default function QuestionMarker(props: {
...
-    } else if (selectedIndex === 0) {
-      newSelected = newSelected.concat(selected.slice(1));
-    } else if (selectedIndex === selected.length - 1) {
-      newSelected = newSelected.concat(selected.slice(0, -1));
-    } else if (selectedIndex > 0) {
-      newSelected = newSelected.concat(
-        selected.slice(0, selectedIndex),
-        selected.slice(selectedIndex + 1),
-      );
+    if (newManuallySelected.has(name)) {
```
Comment (calumtomeny) [inline quizmaster-client-app/src/components/QuizHosting/QuestionMarker.tsx:303]: Could put the delete in the if as it returns true/false if the item exists and is deleted or not. Good to see the array manipulation go.

**Review by calumtomeny — APPROVED** [review]
Looks good.
